### PR TITLE
Show image from page label config dialog

### LINKED ISSUE #295: "Configure Page Labels" needs an option to display the selected image
Could possibly work by going to the start of that image and using AutoImg? At least as a first attempt.

### PR DESCRIPTION
**Pull request by windymilla**
When user clicks on a row in the dialog, jump to the page in the file, so user can see the text there to aid their decision about which type of page it is. If user has Auto Img turned on, the image will show in the image viewer.

Fixes #295

### CODE REVIEW

**Comment by srjfoo** [comment]
Testing on macOS, clicking on the image name in the Configure Page Labels widget takes you to the image, but, while using the arrow to move up and down in the list does actually move the row highlighted, it does not navigate between images. I.e. only clicking will do that. Is it possible for using the arrows to move up and down the list can also navigate to the correct image?

**Comment by windymilla** [comment]
> Is it possible for using the arrows to move up and down the list can also navigate to the correct image?

I'll look into it - should be possible

**Comment by windymilla** [comment]
Two commits:
1. Make arrow key selection show the correct page (& image if Auto Img is on), not just mouse selection.
2. When the dialog pops, select the current page's settings in the dialog, and scroll the list so the current page is just below the top of the dialog.

**Comment by srjfoo** [comment]
> Two commits:
> 1. Make arrow key selection show the correct page (& image if Auto Img is on), not just mouse selection.
> 2. When the dialog pops, select the current page's settings in the dialog, and scroll the list so the current page is just below the top of the dialog.

I must be missing something, because this is not working any differently for me than the previous version. (macOS)

**Comment by srjfoo** [comment]
> > Two commits:
> > 
> > 1. Make arrow key selection show the correct page (& image if Auto Img is on), not just mouse selection.
> > 2. When the dialog pops, select the current page's settings in the dialog, and scroll the list so the current page is just below the top of the dialog.
> 
> ~I must be missing something, because this is not working any differently for me than the previous version. (macOS)~

Update -- I decided to check one other way -- for the previous test, I thought I'd updated my existing branch. Apparently I hadn't. I deleted that old branch and tried again, and it worked just fine, thank you!

**Review by srjfoo — APPROVED** [review]

**Pull request merged**
