### PR TITLE
Add First/Last button to Search dialog

### PR DESCRIPTION
**Pull request by windymilla**
The First/Last button finds the first occurrence of the string in the file if searching forwards, and the last occurrence if searching backwards.

Note that searching backwards can be done by turning on "Reverse" checkbox. The currently selected value of "Reverse" is itself reversed if the First/Last button is Shift clicked, just like the Search button.

So, if "Reverse" is off, click First/Last for the first match, shift-click it for last match. If "Reverse" is on, click First/Last for last match and shift-click it for first match.

Since this behavior is identical to the Search button behavior, it should be intuitive to the user. If not, they don't need to use the Shift key and can just use the Reverse checkbox.

### CODE REVIEW

**Review by srjfoo — APPROVED** [review]
Seems to work just fine.

Personal opinion, only: I honestly don't see a need for it. It's a one-button shortcut for home/end (cmd+up/down arrow) plus find again. I'm far from a minimalist, but I'd rather limit the clutter until we need something. So, it's something of a design philosophy, I guess. You've got users wanting it because they had it before, and it's always harder to take something away than it is to not implement it in the first place.

**Review by tangledhelix — CHANGES_REQUESTED** [review]
After reading the forums I'll have to disagree with Sharon's review. It seems to be something the users want.

However, as implemented I find it confusing. Reading your explanation I understand how it works, but my 2¢ is it would be better simplified:

- Label the button "First"
- On click, it goes to the first match
- No shift-click binding

I could see that if Reverse is checked, going to Last instead could make sense. Is it possible to make the label on the button reactive to the state of the Reverse checkbox, such that if Reverse is checked, the label is Last, but otherwise it's First?

I'd be just as happy not doing that, and having a no-frills "First" button.

**Comment by srjfoo** [comment]
> After reading the forums I'll have to disagree with Sharon's review. It seems to be something the users want.

Part of my review was my personal opinion, and the main reason that I'm not in favor of it is that I just don't see a real need for it -- it adds clutter, and it's not really necessary.

I've accepted that it will probably be implemented, and I hate to be the one voting against some things. My main concern is the "give a mouse a cookie" syndrome (aka "slippery slope"?). The more things like this that are implemented, the more will be requested, and the interface will be nickeled and dimed to death.

That being said, @windymilla has certainly implemented a lot of things that I've asked for, as have you.

**Comment by windymilla** [comment]
Agree with @tangledhelix that it's unnecessarily complicated (though actually simpler to implement) with the Shift-to-reverse option. I'll put up another commit that removes that feature.

**Comment by windymilla** [comment]
> Is it possible to make the label on the button reactive to the state of the Reverse checkbox, such that if Reverse is checked, the label is Last, but otherwise it's First?

My latest commit does this, and removes the Shift-to-reverse complication.

**Comment by srjfoo** [comment]
> > Is it possible to make the label on the button reactive to the state of the Reverse checkbox, such that if Reverse is checked, the label is Last, but otherwise it's First?
> 
> My latest commit does this, and removes the Shift-to-reverse complication.

I'm not seeing this -- it still says `First/Last`. I tried disabling Wrap Around and multi-replace, but those had no effect. Did I misunderstand?

**Review by srjfoo — APPROVED** [review]

**Review by tangledhelix — APPROVED** [review]

**Comment by windymilla** [comment]
> I'll admit that I'm really missing the shift-for-reverse,

If a user says, "hey, I can shift-click on Search, why can't I do that on First/Last?" we can add it in a heartbeat

**Pull request merged**
